name: Deploy to EC2  
on:  
  push:  
    branches:  
      - main

env:
  DEPLOY_PATH: /var/www/blog-api

jobs:  
  deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: 23
      - name: Install dependencies  
        run: npm install  

      - name: Build TypeScript project
        run: npm run build  

      - name: Check SSH connection  
        uses: appleboy/ssh-action@master  
        with:  
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          script: |  
            echo "SSH connection successful"  
            whoami  
            
      - name: Create target directory  
        uses: appleboy/ssh-action@master  
        with:  
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          script: |  
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} ${{ env.DEPLOY_PATH }}

            
      - name: Deploy to EC2  
        uses: appleboy/scp-action@master  
        with:  
          host: ${{ secrets.EC2_HOST }}  
          username: ${{ secrets.EC2_USERNAME }}  
          key: ${{ secrets.EC2_PRIVATE_KEY }}  
          source: ".,!.git,!node_modules"  
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1  
          overwrite: true  


      - name: Setup nvm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
              sudo yum update
              sudo yum install -y nginx
              
              sudo systemctl start nginx
              sudo systemctl enable nginx
              
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
              
              nvm install v23
              cd ${{ env.DEPLOY_PATH }}
              
              npm install
              npm run build > /dev/null
              pm2 delete vite-app
              pm2 start "npx serve -s dist -l 3000" --name "vite-app"
              echo "haider ali"
              pm2 save

              sudo bash -c 'cat > /etc/nginx/conf.d/vite-app.conf <<EOF
              server {
                listen 80;
                server_name _;

                location / {
                proxy_pass http://localhost:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade \$http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host \$host;
                proxy_cache_bypass \$http_upgrade;
                }
                }
                EOF'

            
              sudo nginx -t && sudo systemctl reload nginx

              echo " Deployment finished!"
